In [3]:
import numpy as np

In [4]:
#creating new array
np.empty([3,3], int)

array([[-1400856464,         365, -1343835680],
       [        365,           0,           0],
       [-2147483648,           0, -1343835464]])

In [5]:
#to replicate an array
Arr=np.array([[2,5,7],[4,7,2]], np.int32)
np.empty_like(Arr)

array([[-1345820400,         365,           0],
       [          0,           1,  1027423549]])

In [8]:
#arr of dimension 3 and diagonals alone with 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
#create array filled with ones of float type
np.ones([2,4],float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#to copy dimensions of an array but fill it with ones
arr=np.arange(4, dtype=np.int64)
np.ones_like(arr)

array([1, 1, 1, 1], dtype=int64)

In [13]:
#array filled with zeroes
np.zeros((4,4), float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#to copy dimensions of an array but fill it with zeros
arr=np.arange(4, dtype=np.int64)
np.zeros_like(arr)

array([0, 0, 0, 0], dtype=int64)

In [15]:
#create array of any dimension filled with a particular value (7 here)
np.full((3,3),7,dtype=np.uint)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=uint32)

In [16]:
#same using multiplication
np.ones([3,3], dtype=np.uint)*6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]], dtype=uint32)

In [18]:
#create a replica of an array filled with another value
arr=np.arange(4, dtype=np.int64)
np.full_like(arr,6)

array([6, 6, 6, 6], dtype=int64)

In [19]:
#same with multiplication
np.ones_like(arr)*6

array([6, 6, 6, 6], dtype=int64)

In [20]:
#Creating an array
np.array([1,2,3])

array([1, 2, 3])

In [21]:
#Convert a variable into array
X = [1,2]
np.asarray(X)

array([1, 2])

In [22]:
# convert an array into a matrix
X = np.array([[3,6], [5,7]])
np.asmatrix(X)

matrix([[3, 6],
        [5, 7]])

In [23]:
#type conversion from int to float
x = [1,2]
np.asfarray(x)

array([1., 2.])

In [24]:
np.asarray(x,float)

array([1., 2.])

In [25]:
#convert array into scalar of single element
x=np.array([30])
np.asscalar(x)

30

In [27]:
# crating an array copy (different ids)

x=np.array([31,221,32])
y=np.copy(x)
print(id(x), x)
print(id(y), y)

1570925010416 [ 31 221  32]
1570924616960 [ 31 221  32]


In [28]:
# range => arange(start,end+1,step)
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [33]:
# create a range (1-d Array) with a start value, end value and even spacing (difference)
np.linspace(5.,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [34]:
#create logspaced values in an array
np.logspace(5.,10.,6)

array([1.e+05, 1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10])

In [35]:
#get diagonal of matrix
mat = np.array([[3,6,7,9],[2,5,1,2],[6,8,3,1],[3,5,6,8]])
np.diag(mat)

array([3, 5, 3, 8])

In [36]:
mat.diagonal()

array([3, 5, 3, 8])

In [37]:
#creating an array with diagonals alone specified
np.diagflat([4,7,9,0])

array([[4, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 0]])

In [7]:
# getting any specific element from an array
arr=np.array([[1,2,3],[4,5,6]])
t1=arr.flat[4]
t2=np.ravel(arr)[4]
assert np.allclose(t1,t2) #checking for equality of the arrays
print(t1)
print(t2)

5
5


In [8]:
# echanging dimension of a matrix MxN => NxM
#assert fucntion is used to check whether the given condition is true
arr=np.zeros((5,4))
t1=np.swapaxes(arr,1,0) #method 1
t2=arr.transpose() #method 2
t3=arr.T #method 3
assert t1.shape==t2.shape==t3.shape
print(t1,t2,t3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#adding extra dimension to an array
arr = np.zeros((2,3))
print(np.expand_dims(arr,axis=1).shape)

(2, 1, 3)


In [12]:
#Removing a single dimension
arr=np.zeros((2,4,3))
print(np.squeeze(arr).shape)

(2, 4, 3)


In [18]:
#Concatenating two arrays (column vice)
arr=np.array([[3,2,5],[2,4,6]])
arr1=np.array([[4,3,2],[6,7,9]])
t1=np.concatenate((arr,arr1),1) #method 1
t2=np.hstack((arr,arr1)) #method 2
assert np.allclose(t1,t2)
print(t2)

[[3 2 5 4 3 2]
 [2 4 6 6 7 9]]


In [20]:
#concatenating two arrays (row wise)
arr=np.array([[3,2,5],[2,4,6]])
arr1=np.array([[4,3,2],[6,7,9]])
t1=np.concatenate((arr,arr1),0) #method 1
t2=np.vstack((arr,arr1)) #method 2
assert np.allclose(t1,t2)
print(t2)

[[3 2 5]
 [2 4 6]
 [4 3 2]
 [6 7 9]]


In [21]:
#Various products of matrices
arr1=[2,4]
arr2=[[2,1],[3,4]]
print(np.dot(arr1,arr2))
print(np.dot(arr2,arr1))
print(np.matmul(arr1,arr2))
print(np.inner(arr1,arr2))
print(np.inner(arr2,arr1))

[16 18]
[ 8 22]
[16 18]
[ 8 22]
[ 8 22]


In [24]:
#Vector dot product
x=np.array([[2,4],[4,5]])
y=np.array([[2,1],[3,4]])
print(np.vdot(x,y))
print(np.vdot(y,x))
print(np.dot(x.flatten(),y.flatten()))
print(np.inner(x.flatten(),y.flatten()))
print((x*y).sum())

40
40
40
40
40


In [25]:
#Checking whether all elements are non-zero 
x=np.array([1,2,3])
print(np.all(x))

x=np.array([1,0,3])
print(np.all(x))


True
False


In [26]:
#checking if any of the element is non-zero
x=np.array([1,0,0])
print(np.any(x))

x=np.array([0,0,0])
print(np.any(x))

True
False


In [28]:
#creating array with random values
np.random.random((3,3))

array([[0.09799593, 0.87699258, 0.97083585],
       [0.80380896, 0.0888896 , 0.6469183 ],
       [0.1967608 , 0.24131699, 0.83233442]])

In [30]:
#Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

a1=np.random.randn(1000,1000)
a2=np.random.standard_normal((1000,1000))
a3=np.random.normal(loc=0.0, scale=1.0, size=(1000,1000))
assert np.allclose(np.mean(a1),np.mean(a2), atol=0.1)
assert np.allclose(np.mean(a1),np.mean(a3), atol=0.1)
assert np.allclose(np.std(a1),np.std(a2), atol=0.1)
assert np.allclose(np.std(a1),np.std(a3), atol=0.1)
print(np.mean(a3))
print(np.std(a1))

6.944434336537968e-05
1.0010595186681057


In [31]:
#Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.
np.random.randint(0, 4, (3, 2))

array([[0, 1],
       [2, 3],
       [1, 3]])

In [32]:
#Selecting random values in a range without repetition (same probability)
np.random.choice(10, 3, replace=False)

array([2, 3, 9])

In [35]:
#shuffling values in a data structure
x=np.arange(7)
np.random.shuffle(x)
print(x)
print(np.random.permutation(7))

[6 0 3 1 5 2 4]
[2 6 4 0 1 3 5]


In [37]:
#Random Number genration with a seed value so the same value can obtained next time
print(np.random.seed(13))

None
