In [3]:
import numpy as np

In [4]:
#creating new array
np.empty([3,3], int)

array([[-1400856464,         365, -1343835680],
       [        365,           0,           0],
       [-2147483648,           0, -1343835464]])

In [5]:
#to replicate an array
Arr=np.array([[2,5,7],[4,7,2]], np.int32)
np.empty_like(Arr)

array([[-1345820400,         365,           0],
       [          0,           1,  1027423549]])

In [8]:
#arr of dimension 3 and diagonals alone with 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
#create array filled with ones of float type
np.ones([2,4],float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#to copy dimensions of an array but fill it with ones
arr=np.arange(4, dtype=np.int64)
np.ones_like(arr)

array([1, 1, 1, 1], dtype=int64)

In [13]:
#array filled with zeroes
np.zeros((4,4), float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#to copy dimensions of an array but fill it with zeros
arr=np.arange(4, dtype=np.int64)
np.zeros_like(arr)

array([0, 0, 0, 0], dtype=int64)

In [15]:
#create array of any dimension filled with a particular value (7 here)
np.full((3,3),7,dtype=np.uint)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=uint32)

In [16]:
#same using multiplication
np.ones([3,3], dtype=np.uint)*6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]], dtype=uint32)

In [18]:
#create a replica of an array filled with another value
arr=np.arange(4, dtype=np.int64)
np.full_like(arr,6)

array([6, 6, 6, 6], dtype=int64)

In [19]:
#same with multiplication
np.ones_like(arr)*6

array([6, 6, 6, 6], dtype=int64)

In [20]:
#Creating an array
np.array([1,2,3])

array([1, 2, 3])

In [21]:
#Convert a variable into array
X = [1,2]
np.asarray(X)

array([1, 2])

In [22]:
# convert an array into a matrix
X = np.array([[3,6], [5,7]])
np.asmatrix(X)

matrix([[3, 6],
        [5, 7]])

In [23]:
#type conversion from int to float
x = [1,2]
np.asfarray(x)

array([1., 2.])

In [24]:
np.asarray(x,float)

array([1., 2.])

In [25]:
#convert array into scalar of single element
x=np.array([30])
np.asscalar(x)

30

In [27]:
# crating an array copy (different ids)

x=np.array([31,221,32])
y=np.copy(x)
print(id(x), x)
print(id(y), y)

1570925010416 [ 31 221  32]
1570924616960 [ 31 221  32]


In [28]:
# range => arange(start,end+1,step)
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [33]:
# create a range (1-d Array) with a start value, end value and even spacing (difference)
np.linspace(5.,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [34]:
#create logspaced values in an array
np.logspace(5.,10.,6)

array([1.e+05, 1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10])

In [35]:
#get diagonal of matrix
mat = np.array([[3,6,7,9],[2,5,1,2],[6,8,3,1],[3,5,6,8]])
np.diag(mat)

array([3, 5, 3, 8])

In [36]:
mat.diagonal()

array([3, 5, 3, 8])

In [37]:
#creating an array with diagonals alone specified
np.diagflat([4,7,9,0])

array([[4, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 0]])